### ISSUE TITLE
Social media images have invalid format

### ISSUE THREAD

**Issue by Sebobo** [neos/Neos.NeosIo#298]
For some reason they don't have absolute urls on production.
In local development they have absolute urls.

<img width="939" alt="Bildschirmfoto 2019-11-07 um 18 28 10" src="https://user-images.githubusercontent.com/596967/68412429-7ba9db80-018c-11ea-9bf8-7ccfb5321b4f.png">

This creates issues with Twitter and FACEBOOK, etc...

**Comment by Sebobo** [comment]
@robertlemke I think we talked about this issue before and it was related to `BEACH_PERSISTENT_RESOURCES_BASE_PATH`?

**Comment by markusguenther** [comment]
Do you use that config also on live?

```
Neos:
  Flow:
    resource:
      targets:
        localWebDirectoryStaticResourcesTarget:
          targetOptions:
            relativeSymlinks: true

        localWebDirectoryPersistentResourcesTarget:
          targetOptions:
            relativeSymlinks: true
```
